Use the AzApi provider rather than wrapping the ARM template
garnertb/github-runner-vnet pull request #11
Opened 2024-07-22 09:51 UTC by ilmax

I think the AzApi provider is a the better option to use here, it's less verbose due to not requiring the ARM file. This should not have any meaningful change and the outcome should be the same. I use this exact resource to create the GitHub network setting resource in my environment and it works just fine.

Also I fixed the variable names in the example so terraform validate now works on both of them.

P.S. Thanks for putting this together :)

2024-07-31 19:39 UTC, pwideman commented
Thanks for the contributions @ilmax. Couple of things here:

1. There are actually a few more places where var names need to be fixed up to align to the new "business" ID instead of enterprise ID. I also think we should keep those changes separate from your more important AzApi changes, so we'll have a cleaner commit history and such. I will make those changes in a separate PR.
2. This repo contains two TF modules, in `/modules/nsg` and `/modules/firewall`. Your AzApi changes need to be made in both modules, not just the firewall module.

Otherwise, I agree that using the AzApi resource provider is cleaner than the ARM template. Have you verified that `terraform destroy` will delete the `networkSettings` resource? I will try this out myself as well.

2024-07-31 20:01 UTC, pwideman requested changes

2024-07-31 20:01 UTC, pwideman commented on examples/example-firewall/main.tf
> +    github_business_id = var.github_enterprise_id
There's a few other places where similar changes need to be made, I've created another PR to handle these so let's roll these back here.

2024-07-31 20:01 UTC, pwideman commented on examples/example-nsg/main.tf
> +    github_business_id = var.github_enterprise_id
See above - let's roll this back here and I'll submit a more comprehensive fix.

2024-07-31 20:01 UTC, pwideman commented on modules/firewall/main.tf
> +  }
These changes look good but the `/modules/nsg` module also needs to be updated with the same changes.

2024-08-01 06:15 UTC, ilmax commented
> This repo contains two TF modules, in /modules/nsg and /modules/firewall. Your AzApi changes need to be made in both modules, not just the firewall module.

I somehow missed this 🤷 it's fixed now. Let me know if you prefer me to rebase the changes into a single commit.

> This repo contains two TF modules, in /modules/nsg and /modules/firewall. Your AzApi changes need to be made in both modules, not just the firewall module.

Honestly nope, but in the worst case, we can use something akin to [this](https://github.com/Azure/terraform-provider-azapi/issues/314) to force a deletion when issuing `terraform destroy`

2024-08-06 15:06 UTC, pwideman commented
@ilmax no need to rebase, we will squash and merge anyway.

The code changes look good, but deletion of the `GitHub.Network/networkSettings` resources needs to be confirmed before we can accept this. I still plan on testing it myself but not sure when I will find time.

2024-08-06 17:54 UTC, pwideman requested changes
I tested this, creation and delete. Delete works fine with how `azapi` is currently being used, nothing else to do there. However there were validation and runtime errors that should have been readily apparent with any testing. I've provided comments to show what needs to be changed to fix those errors.

Also, your `main` branch is not up to date with `garnertb:main` after I fixed the business/enterprise ID variable issues. It shouldn't cause a problem for this PR because the differences do not overlap, but you still probably want to update your repo.

2024-08-06 17:54 UTC, pwideman commented on modules/firewall/outputs.tf
> +    value = jsondecode(azapi_resource.github_network_settings.output).gitHubId.value
This is wrong and results in a runtime error, it should be:
```suggestion
    value = jsondecode(azapi_resource.github_network_settings.output).tags.GitHubId
```

2024-08-06 17:54 UTC, pwideman commented on modules/nsg/outputs.tf
> +    value = jsondecode(azapi_resource.github_network_settings.output).gitHubId.value
This is wrong and results in a runtime error, it should be:
```suggestion
    value = jsondecode(azapi_resource.github_network_settings.output).tags.GitHubId
```

2024-08-06 17:54 UTC, pwideman commented on modules/nsg/main.tf
This file needs the `azapi` required provider just like `modules/firewall/main.tf`:

```
    azapi = {
      source  = "Azure/azapi"
      version = "~> 1.14.0"
    }
```

2024-08-06 18:24 UTC, ilmax commented
Thanks for checking this one out, let me resolve the issues that are a copy-paste error.

2024-08-07 13:08 UTC, pwideman commented
> I apologize for the issue that was a copy-paste error, I didn't apply this configuration, I just backported some of the changes I made because I thought it could improve this repo 🤷

No worries there, they are good contributions that are much appreciated, and we'll get the kinks worked out.

2024-08-07 23:04 UTC, pwideman approved these changes

2024-08-07 23:05 UTC, merged